#!/usr/bin/env python

import ConfigParser
import sys, os, io
from os.path import expanduser

home = expanduser("~")
keyfile = home+"/.ssh/foreign.pub"
configfile = home+"/.ssh/connect.config"

if not os.path.isfile(configfile):
    cfgfile = open(configfile, 'w')
    config = ConfigParser.ConfigParser()
    config.write(cfgfile)
    config.close()

config = ConfigParser.ConfigParser()
config.read(configfile)

def connect_to(nickname):
	try:
		connection_string = config.get(nickname, 'connection_string')
		result = "ssh " + connection_string
		os.system(result)
	except:
		print("Cannot find any servers related to "+nickname+". Please create it (connect user@host nickname).")

def create_connection(connection_string, nickname):
	result = "ssh-copy-id -i "+keyfile+" "+connection_string
	os.system(result)
	config.add_section(nickname)
	config.set(nickname, 'connection_string', connection_string)
	with open(configfile, 'wb') as configure:
		config.write(configure)


if len(sys.argv) == 2:
	connect_to(sys.argv[1])
else:
	if len(sys.argv) == 3:
		create_connection(sys.argv[1], sys.argv[2])
	else:
		print("Usage:\n")
		print("connect user@host nickname - create connection")
		print("connect nickname - connect to existing server")
