#!/usr/bin/env python

import ConfigParser
import sys, os, io
from os.path import expanduser

keyname = "foreign.pub"
sshdir = expanduser("~")+"/.ssh/"
keyfile = sshdir+keyname
configfile = sshdir+"connect.config"

if not os.path.isfile(configfile):
    cfgfile = open(configfile, 'w')
    config = ConfigParser.ConfigParser()
    config.write(cfgfile)
    config.close()

config = ConfigParser.ConfigParser()
config.read(configfile)

def connect_to(nickname):
	try:
		connection_string = config.get(nickname, 'connection_string')
		result = "ssh " + connection_string
		os.system(result)
	except:
		print("Cannot find any servers related to "+nickname+". Please create it (connect user@host nickname).")

def create_connection(connection_string, nickname):
	result = "ssh-copy-id -i "+keyfile+" "+connection_string
	os.system(result)
	config.add_section(nickname)
	config.set(nickname, 'connection_string', connection_string)
	with open(configfile, 'wb') as configure:
		config.write(configure)

def show_connections():
	connections = config.sections()
	for connection in connections:
		print("Nickname: "+connection)
		print("    Connection string: "+config.items(connection)[0][1])

if len(sys.argv) == 2:
	if(sys.argv[1] == 'show'):
		show_connections()
	else:
		connect_to(sys.argv[1])
else:
	if len(sys.argv) == 3:
		create_connection(sys.argv[1], sys.argv[2])
	else:
		print("Usage:\n")
		print("connect user@host nickname - create connection")
		print("connect nickname - connect to existing server")
		print("connect show - show saved connections")
